source 'https://github.com/CocoaPods/Specs.git'

target 'NavigationKit', :exclusive => true do
  pod "NavigationKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "NavigationKit", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
end
